spring:
  application:
    name: aggregate-service
  profiles:
    active: development
  cloud:
    stream:
      bindings:
        user-input:
          destination: user
          group: user-group
          contentType: 'application/json'
          consumer:
            concurrency: 1
        friend-input:
          destination: friend
          group: friend-group
          contentType: 'application/json'
          consumer:
            concurrency: 1
      kafka:
        binder:
          brokers: localhost:9092
#          zkNodes: localhost
#          defaultZkPort: 2181
#          defaultBrokerPort: 9092 
      binders:
        kafka:
          default-candidate: true
  data:
    neo4j:
      uri: http://localhost:7474
      username: neo4j
      password: secret
      
                            
server:
  port: 8083
---
spring:
  profiles: development
  data:
    neo4j:
      uri: http://localhost:7474
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  data:
    neo4j:
      uri: http://neo4j:7474
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          defaultBrokerPort: 29092
          zkNodes: zookeeper
          defaultZkPort: 32181
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test